services:
  app_proxy:
    environment:
      APP_HOST: cryptoice-bitlink21_bitlink21_1
      APP_PORT: 7000

  bitlink21:
    image: ghcr.io/cryptoicemlh/bitlink21:v3.0.0
    restart: unless-stopped
    environment:
      PLUTO_URI: "${APP_CRYPTOICE_BITLINK21_PLUTO_URI}"
      BITLINK21_DB_PATH: "/app/backend/data/bitlink21.db"
      BITCOIN_RPC_URL: "${APP_CRYPTOICE_BITLINK21_BITCOIN_RPC_URL:-}"
      BITCOIN_RPC_USER: "${APP_CRYPTOICE_BITLINK21_BITCOIN_RPC_USER:-}"
      BITCOIN_RPC_PASS: "${APP_CRYPTOICE_BITLINK21_BITCOIN_RPC_PASS:-}"
      LND_REST_URL: "${APP_CRYPTOICE_BITLINK21_LND_REST_URL:-}"
    volumes:
      - ${APP_DATA_DIR}/data:/app/backend/data
